---
- name: Setup kubeconfig for user
  become: false
  register: user_id
  ansible.builtin.command: whoami

- name: Setup and install various features
  become: false
  become_user: "{{ user_id.stdout }}"
  block:
  - name: Mkdir for user config
    ansible.builtin.file:
      path: ~/.kube
      state: directory

  - name: Copy kubeconfig file
    ansible.builtin.copy:
      src: ./kubeconfig
      dest: ~/.kube/config 

  - name: Wait for apiserver to be ready
    register: apiserver_ready
    ansible.builtin.command: "kubectl get nodes"
    retries: 100
    delay: 10

  - name: Debug
    debug:
      msg: "{{ apiserver_ready }}"

  - name: Install Nginx ingress controller
    ansible.builtin.shell: |
      kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-{{ nginx_ingress_version }}/deploy/static/provider/baremetal/deploy.yaml

  - name: Install Metrics server
    when: "(no_metrics_server is undefined) or (no_metrics_server|bool == false)"
    block:
    - name: Upload Metrics server manifests
      ansible.builtin.copy:
        src: metrics-server
        dest: ~/

    - name: Install Metrics server
      ansible.builtin.shell: kubectl apply -f metrics-server/

  - name: Clean up after setup
    ansible.builtin.file:
      path: ~/.kube
      state: absent

