apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailroom
  labels:
    app: mailroom
    app.kubernetes.io/name: mailroom
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: mailroom
{{ include "rapidpro-stack.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailroom
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: mailroom
        app.kubernetes.io/name: mailroom
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: mailroom
    spec:
      serviceAccountName: {{ .Values.mailroom.serviceAccountName }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: mailroom
      securityContext:
      {{- toYaml .Values.mailroom.podSecurityContext | nindent 8 }}
      containers:
      - image: {{ .Values.registry.host }}/{{ .Values.mailroom.image.name }}:{{ .Values.mailroom.image.version }}
        name: mailroom 
        imagePullPolicy: {{ .Values.mailroom.image.pullPolicy }}
        securityContext:
        {{- toYaml .Values.mailroom.securityContext | nindent 10 }}
        ports:
        - containerPort: 8090
          protocol: TCP
        envFrom:
        - configMapRef:
            name: database-host
        - secretRef: 
            name: {{ .Values.databaseCredentialsSecret }}
        - secretRef:
            name: redis-connection
        env:
        - name: BACKEND_URL
          value: http://rapidpro-svc:8080
        - name: MAILROOM_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: mailroom-token
              key: token
        resources:
        {{- toYaml .Values.mailroom.resources | nindent 10 }}
---
