---
apiVersion: v1
kind: Service
metadata:
  name: mailroom-svc
  labels:
    app.kubernetes.io/name: mailroom-svc
    app.kubernetes.io/component: endpoint
    app.kubernetes.io/part-of: mailroom
{{ include "rapidpro-stack.labels" . | indent 4 }}
spec:
  selector:
    app: mailroom
  ports:
  - port: 8090
    targetPort: 8090
---