---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels.selectors | nindent 6 }}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels.pod | nindent 8 }}
        {{- if .Values.global.labels }}
          {{- toYaml .Values.global.labels | nindent 8 }}
        {{- end }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
        {{- if .Values.global.annotations }}
          {{- toYaml .Values.global.annotations | nindent 8 }}
        {{- end }}
    spec:
      topologySpreadConstraints:
        {{- toYaml .Values.topologySpreadConstraints | nindent 6 }}
      volumes:
      - name: nginx-conf
        projected:
          sources:
            - configMap:
                name: courier-nginx
      containers:
      - image: nginx:alpine
        name: proxy
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/
      - image: {{ .Values.global.registry.host }}/{{ .Values.image.name }}:{{ .Values.image.version }}
        name: courier
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: database-host
        - configMapRef:
            name: redis-host
        - secretRef:
            name: {{ .Values.global.databaseCredentials.name }}
        env:
        - name: BACKEND_URL
          value: http://rapidpro-svc:8080
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
---
