---
- hosts: database
  become: yes
  vars:
    pg_user: temba
    pg_password: temba
  roles:
  - ./postgresql

- hosts: registry
  become: yes
  vars:
    registry_username: temba
    registry_userpasswd: temba 
    registry_ca_dir: /tmp/rapidpro/registry-ca/
  roles:
  - ./registry

- name: Kubernetes playbook 
  import_playbook: ./roles/k8s/main.yml
  vars:
    registry_ca_dir: /tmp/rapidpro/registry-ca/
