---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier
  labels:
    app.kubernetes.io/name: courier
    app.kubernetes.io/component: courier
    app.kubernetes.io/part-of: rapidpro
{{ include "rapidpro-stack.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: courier
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: courier
        app.kubernetes.io/component: courier
        app.kubernetes.io/part-of: rapidpro
    spec:
      serviceAccountName: {{ .Values.courier.serviceAccountName }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: courier
      securityContext:
      {{- toYaml .Values.courier.podSecurityContext | nindent 8 }}
      volumes:
      - name: nginx-conf
        projected:
          sources:
            - configMap:
                name: courier-nginx 
      containers:
      - image: nginx:alpine
        name: proxy
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/
      - image: {{ .Values.registry.host }}/{{ .Values.courier.image.name }}:{{ .Values.courier.image.version }}
        name: courier
        imagePullPolicy: {{ .Values.courier.image.pullPolicy }}
        securityContext:
        {{- toYaml .Values.courier.securityContext | nindent 10 }}
        ports:
        - containerPort: 8080 
          protocol: TCP
        envFrom:
        - configMapRef:
            name: database-host
        - secretRef:
            name: {{ .Values.databaseCredentialsSecret }}
        - secretRef: 
            name: redis-connection
        env:
        - name: BACKEND_URL
          value: http://rapidpro-svc:8080
        resources:
        {{- toYaml .Values.courier.resources | nindent 10 }}
---
