imagePullSecrets:
  - registry

# Required keys are:
# ADMIN_USERNAME
# ADMIN_PASSWORD
# ADMIN_EMAIL
adminCredentialsSecret: admin-credentials

# This chart will install a redis server
redis:
  url: redis://redis:6379

# Required keys are:
# POSTGRES_USER
# POSTGRES_PASSWORD
# POSTGRES_DB
databaseCredentialsSecret: database-credentials

databaseHost:
  postgres:
    host: "172.20.0.3"
    port: 5432

registry:
  host: "172.20.0.2"

courier:
  image:
    name: courier
    version: v7.4.0
  serviceAccountName: rapidpro
  securityContext:
    capabilities: { }
    runAsNonRoot: true
    runAsUser: 1001
    allowPrivilegeEscalation: false
  podSecurityContext:
    fsGroup: 2000
  imagePullPolicy: IfNotPresent
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

mailroom:
  image:
    name: mailroom
    version: v7.4.1
  serviceAccountName: rapidpro
  securityContext:
    capabilities: { }
    runAsNonRoot: true
    runAsUser: 1001
    allowPrivilegeEscalation: false
  podSecurityContext:
    fsGroup: 2000
  imagePullPolicy: IfNotPresent
  resources: {}

rapidpro:
  image:
    name: rapidpro
    version: v7.4.0
    pullPolicy: IfNotPresent
  serviceAccountName: rapidpro
  app: 
    securityContext:
      capabilities: { }
      runAsNonRoot: true
      runAsUser: 1001
      allowPrivilegeEscalation: false
    podSecurityContext:
      fsGroup: 2000
    resources: { }
  celery: 
    securityContext:
      capabilities: { }
      runAsNonRoot: true
      runAsUser: 1001
      allowPrivilegeEscalation: false
    podSecurityContext:
      fsGroup: 2000
    resources: { }
  migrations:
    securityContext:
      capabilities: { }
      runAsNonRoot: true
      runAsUser: 1001
      allowPrivilegeEscalation: false
    podSecurityContext:
      fsGroup: 2000
    resources: { }
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
