global:
  imagePullSecrets:
    - registry

  # Required keys are:
  # ADMIN_USERNAME
  # ADMIN_PASSWORD
  # ADMIN_EMAIL
  adminCredentialsSecret: admin-credentials

  # The chart will install a redis server
  # TODO add redis chart as a dependency
  redis:
    url: redis://redis:6379

  # Required keys are:
  # POSTGRES_USER
  # POSTGRES_PASSWORD
  # POSTGRES_DB
  databaseCredentialsSecret: database-credentials

  databaseHost:
    postgres:
      host: ""
      port: 5432

  registry:
    host: ""

  labels: {}
  annotations: {}

courier:
  image:
    name: courier
    version: v7.4.0
    pullPolicy: IfNotPresent
  serviceAccountName: rapidpro
  replicaCount: 1

mailroom:
  image:
    name: mailroom
    version: v7.4.1
    pullPolicy: IfNotPresent
  serviceAccountName: rapidpro
  replicaCount: 1

rapidpro:
  image:
    name: rapidpro
    version: v7.4.2
    pullPolicy: Always
  serviceAccountName: rapidpro
  replicaCount: 1

