apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  labels:
    app.kubernetes.io/name: migrations
    app.kubernetes.io/component: migrations
    app.kubernetes.io/part-of: stack
{{ include "rapidpro-stack.labels" . | indent 4 }} 
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.rapidpro.serviceAccoutName }}
      securityContext:
      {{- toYaml .Values.rapidpro.migrations.podSecurityContext | nindent 8 }}
      containers:
      - image: {{ .Values.registry.host }}/{{ .Values.rapidpro.image.name }}:{{ .Values.rapidpro.image.version }}
        name: migrations 
        imagePullPolicy: {{ .Values.rapidpro.image.pullPolicy }}
        securityContext:
        {{- toYaml .Values.rapidpro.migrations.securityContext | nindent 10 }}
        args:
        - -c
        - ./migrate.sh
        envFrom:
        - configMapRef:
            name: database-host
        - secretRef:
            name: {{ .Values.databaseCredentialsSecret }}
        - secretRef:
            name: redis-connection
        - secretRef:
            name: admin-credentials
        resources:
        {{- toYaml .Values.rapidpro.migrations.resources | nindent 10 }}
---