---
apiVersion: v1
kind: Service
metadata:
  name: rapidpro-svc
  labels:
    app.kubernetes.io/name: rapidpro-svc
    app.kubernetes.io/component: endpoint
    app.kubernetes.io/part-of: rapidpro
{{ include "rapidpro-stack.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rapidpro-app
    app.kubernetes.io/component: application
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8000
---