---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-host
data:
  POSTGRES_HOST: "{{ .Values.global.databaseHost.postgres.host }}"
  POSTGRES_PORT: "{{ .Values.global.databaseHost.postgres.port }}"
---

