apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  labels:
    app.kubernetes.io/name: migrations
    app.kubernetes.io/component: migrations
    app.kubernetes.io/part-of: stack
{{ include "rapidpro-stack.labels" . | indent 4 }} 
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: rapidpro
      securityContext:
      {{- toYaml .Values.podSecurityContext.rapidpro | nindent 8 }}
      containers:
      - image: {{ .Values.stack.registry.host }}/{{ .Values.stack.rapidpro.name }}:{{ .Values.stack.rapidpro.version }}
        name: migrations 
        imagePullPolicy: {{ .Values.imagePullPolicy.rapidpro }}
        securityContext:
        {{- toYaml .Values.securityContext.rapidpro | nindent 10 }}
        args:
        - -c
        - ./migrate.sh
        envFrom:
        - configMapRef:
            name: database-host
        - secretRef:
            name: {{ .Values.databaseCredentialsSecret }}
        - secretRef:
            name: redis-connection
        - secretRef:
            name: admin-credentials
        resources:
        {{- toYaml .Values.resources.rapidpro.migrations | nindent 10 }}
