apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rapidpro-ingress
  labels:
    app: rapidpro
    app.kubernetes.io/name: rapidpro-ingress
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: rapidpro
{{ include "rapidpro-stack.labels" . | indent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rapidpro-svc
            port:
              number: 8080
