apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: stack
{{ include "rapidpro-stack.labels" . | indent 4 }}
spec:
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
  containers:
  - name: redis
    image: redis:alpine
    ports:
    - containerPort: 6379
      protocol: TCP
      name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: endpoint
    app.kubernetes.io/part-of: stack
{{ include "rapidpro-stack.labels" . | indent 4 }}
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    protocol: TCP
    targetPort: redis
