---
apiVersion: v1
kind: Secret
metadata:
  name: redis-connection
  labels:
    app: rapidpro-stack
    app.kubernetes.io/name: rapidpro-stack
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: stack
stringData:
  REDIS_URL: {{ .Values.redis.url }}
---
apiVersion: v1
data:
  token: {{ uuidv4 | b64enc }}
kind: Secret
metadata:
  name: mailroom-token
  labels:
    app.kubernetes.io/name: mailroom-token
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: stack
{{ include "rapidpro-stack.labels" . | indent 4 }}
---
