{{ if .Values.global.adminCredentials.credentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.adminCredentials.name }}
  labels:
{{ include "rapidpro-stack.labels" . | indent 4 }}
stringData:
  ADMIN_USERNAME: {{ .Values.global.adminCredentials.credentials.user }}
  ADMIN_PASSWORD: {{ .Values.global.adminCredentials.credentials.password }}
  ADMIN_EMAIL: {{ .Values.global.adminCredentials.credentials.email }}
---
{{ end }}
{{ if .Values.global.databaseCredentials.credentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.databaseCredentials.name }}
  labels:
{{ include "rapidpro-stack.labels" . | indent 4 }}
stringData:
  POSTGRES_USER: {{ .Values.global.databaseCredentials.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.global.databaseCredentials.credentials.password }}
  POSTGRES_DB: {{ .Values.global.databaseCredentials.credentials.database }}
---
{{ end }}
