{{- define "imagePullSecret" }}
{{- with .Values.imageCredentials }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}
---
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: registry
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: stack
{{ include "rapidpro-stack.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: database-connection
  labels:
    app: rapidpro-stack
    app.kubernetes.io/name: rapidpro-stack
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: stack
stringData:
  POSTGRES_HOST: postgresql
data:
  POSTGRES_PORT: {{ .Values.databaseCredentials.pg_port | print | b64enc }}
  POSTGRES_USER: {{ .Values.databaseCredentials.pg_user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.databaseCredentials.pg_password | b64enc }} 
#  POSTGRES_HOST: {{ .Values.databaseCredentials.pg_host | b64enc }}
  POSTGRES_DB: {{ .Values.databaseCredentials.pg_db | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-credentials
  labels:
    app: rapidpro
    app.kubernetes.io/name: rapidpro
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: stack
data:
  ADMIN_USERNAME: {{ .Values.adminCredentials.username | b64enc }}
  ADMIN_PASSWORD: {{ .Values.adminCredentials.password | b64enc }}
  ADMIN_EMAIL: {{ .Values.adminCredentials.email | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-connection
  labels:
    app: rapidpro-stack
    app.kubernetes.io/name: rapidpro-stack
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: stack
stringData:
  REDIS_URL: {{ .Values.redis.url }}
---
apiVersion: v1
data:
  token: {{ uuidv4 | b64enc }}
kind: Secret
metadata:
  name: mailroom-token
  labels:
    app.kubernetes.io/name: mailroom-token
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: stack
{{ include "rapidpro-stack.labels" . | indent 4 }}
---
