---
apiVersion: v1
kind: Secret
metadata:
  name: redis-connection
  labels:
    app: rapidpro-stack
    app.kubernetes.io/name: rapidpro-stack
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: stack
stringData:
  REDIS_URL: {{ .Values.redis.url }}
---
