apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rapidpro-ingress
  labels:
    {{- toYaml .Values.ingress.labels | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rapidpro-svc
            port:
              number: 8080
