apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
spec:
  backoffLimit: 5
  completions: 10
  template:
    spec:
      restartPolicy: {{ .Values.migrations.restartPolicy }}
      serviceAccountName: {{ .Values.serviceAccoutName }}
      securityContext:
        {{- toYaml .Values.migrations.podSecurityContext | nindent 8 }}
      containers:
      - image: {{ .Values.global.registry.host }}/{{ .Values.image.name }}:{{ .Values.image.version }}
        name: migrations 
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.migrations.securityContext | nindent 10 }}
        args:
        - -c
        - ./migrate.sh
        envFrom:
        - configMapRef:
            name: database-host
        - configMapRef:
            name: redis-host
        - secretRef:
            name: {{ .Values.global.databaseCredentials.name }}
        - secretRef:
            name: {{ .Values.global.adminCredentials.name }}
        resources:
          {{- toYaml .Values.migrations.resources | nindent 10 }}
---
